project_name: "goignore"

before:
  hooks:
    - go mod tidy

builds:
  - id: "goignore"
    dir: "."
    main: "./cmd/goignore"
    binary: "goignore"
    ldflags:
      - -s -w
      - -X github.com/FollowTheProcess/goignore/cli.version={{.Version}}
      - -X github.com/FollowTheProcess/goignore/cli.commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64

brews:
  - goarm: "6"
    tap:
      owner: FollowTheProcess
      name: homebrew-tap
      token: "{{.Env.HOMEBREW_TAP_TOKEN}}"
    folder: Formula
    commit_author:
      name: Tom Fleet
      email: tomfleet2018@gmail.com
    homepage: https://github.com/FollowTheProcess/goignore
    description: Easy gitignores from the command line.
    license: MIT License
    install: |
      bin.install "goignore"
    test: |
      "#{bin}/goignore version"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  # The changelog is handled by release drafter
  skip: true
